added assignment4
shivani-tr/FE-Assignment1 pull request #13
Opened 2024-11-26 12:19 UTC by shivani-tr

2024-11-27 08:15 UTC, gauravvolopay requested changes

2024-11-27 08:15 UTC, gauravvolopay commented on assignment2/src/components/core/ProductTable.jsx
> +
Use the same Table core component which u have use for losers and gainers

2024-11-27 08:15 UTC, gauravvolopay commented on assignment2/src/components/core/TableButtons.jsx
> +import { useSelector, useDispatch } from "react-redux";
Remove it from the core folder, it is not a core component

2024-11-27 08:15 UTC, gauravvolopay commented on assignment2/src/components/InfiniteScroll.jsx
> +    const products = useSelector((state) => state.product.products);
Create a selectors file then use those selectors here to get the values here

2024-11-27 10:50 UTC, shivani-tr commented on assignment2/src/components/core/ProductTable.jsx
> +
Updated Table.jsx to be reusable

2024-11-27 10:51 UTC, shivani-tr commented on assignment2/src/components/core/TableButtons.jsx
> +import { useSelector, useDispatch } from "react-redux";
Moved TableButtons.jsx inside products folder inside components

2024-11-27 10:51 UTC, shivani-tr commented on assignment2/src/components/InfiniteScroll.jsx
> +    const products = useSelector((state) => state.product.products);
a seperate ProductsSelectors.js created

2024-11-28 04:42 UTC, gauravvolopay approved these changes

2024-11-28 04:43 UTC, merged