Basic project structure
shivani-tr/FE-Assignment1 pull request #15
Opened 2024-11-29 10:44 UTC by shivani-tr

2024-12-02 14:16 UTC, gauravvolopay requested changes

2024-12-02 14:16 UTC, gauravvolopay commented on assignment2/src/components/products/Modal.jsx
> +import { useState, useEffect } from "react";
Make the modal a dumb component, this modal cannot be reused if required showing any other content for some other purpose.

2024-12-05 06:36 UTC, gauravvolopay approved these changes

2024-12-05 06:37 UTC, shivani-tr commented on assignment2/src/components/products/Modal.jsx
> +import { useState, useEffect } from "react";
Resolved

2024-12-05 06:37 UTC, merged